<?
/**********************************************************************************
*                            IBDW EvoWall for Dolphin Smart Community Builder
*                              -------------------
*     begin                : July 23 2012
*     copyright            : (C) 2012 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW EvoWall is not free and you cannot redistribute and/or modify it.
* 
* IBDW EvoWall is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details see license.txt file; if not, write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'evowall';
$aLangContent = array(
'_sys_module_evowall' => 'News Feed',
'_ibdw_evowall_informations'  => 'IBDW EvoWall information',
'_ibdw_evowall_information_block' => 'To get your "License Key" (Activation Code), click <a target="_blank" href="ibdw/evowall/activation.php">HERE</a><br /><br />Remember to insert <b>the same email address you have used to buy this module</b>.<br /><br />After completing these steps, check your email and put the code received into the first field of the following form:',
'_ibdw_evowall_comment_add' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">added a comment to <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_member_subscribed' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined</span>',
'_ibdw_evowall_spyprofile' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">viewed the profile of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_profile_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed own profile</span>',
'_ibdw_evowall_profile_rate' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">rated the profile <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_isfriend' => '<a class="usernamestyle" href="{recipient_p_link}">{recipient_p_nick}</a> <span class="actionx">is now friend with <a href="{sender_p_link}">{sender_p_nick}</a></span>',
'_ibdw_evowall_site_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the site <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_site_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the site <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_site_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the site <a href="{site_url}">{site_caption}</a></span>',	
'_ibdw_evowall_comment_nphoto' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the <a href="{entry_url}">photo</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_comment_name' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the <a href="{entry_url}">video</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_rated_videos' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the <a href="{entry_url}">video</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_reply_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">replied to the <a href="{entry_url}">poll</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_rated_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the <a href="{entry_url}">poll</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_comment_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the <a href="{entry_url}">poll</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_rate_photo' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the <a href="{entry_url}">photo</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_ads_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the ad <a href="{ads_url}">{ads_caption}</a></span>',
'_ibdw_evowall_ads_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new ad <a href="{ads_url}">{ads_caption}</a></span>',
'_ibdw_evowall_blogs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_blogs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_blogs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_sounds_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new music <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_sounds_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the <a href="{entry_url}">music</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_sounds_rate'=> '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the music <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_photo_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new photo <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_video_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new video <a href="{video_url}">{entry_caption}</a></span>',
'_ibdw_evowall_site_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new site <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_group_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">created the group <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_group_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the group <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_group_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined the group <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_group_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the group <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_group_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the group <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a new event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined at the event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_poll_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added a Poll <a href="{poll_url}">{poll_caption}</a></span>',
'_ibdw_evowall_original_size' => 'See you in its original format',
'_ibdw_evowall_event_name' => 'Event',
'_ibdw_evowall_group_forum' => 'Discussion Group',
'_ibdw_evowall_oneminute' => 'about one minute ago',
'_ibdw_evowall_plusminutefirst' => 'about ',
'_ibdw_evowall_plusminutesecond' => ' minutes ago',
'_ibdw_evowall_onehour' => 'about 1 hour ago',
'_ibdw_evowall_plushourfirst' => 'about ',
'_ibdw_evowall_plushoursecond' => ' hours ago',
'_ibdw_evowall_today' => 'today',
'_ibdw_evowall_yesterday' => 'yesterday',
'_ibdw_evowall_otherday' => 'added ',
'_ibdw_evowall_now' => 'now added',
'_ibdw_evowall_comment_title_first' => 'Be the first',
'_ibdw_evowall_comment_title1' => 'There is',
'_ibdw_evowall_comment_title2' => 'There are',
'_ibdw_evowall_comment_titlef1' => 'comment',
'_ibdw_evowall_comment_titlef2' => 'comments',
'_ibdw_evowall_ins_comm' => 'Comment',
'_ibdw_evowall_condividi' => 'Share',
'_ibdw_evowall_altrenews' => 'Older News',
'_ibdw_evowall_fotoup' => 'Photo',
'_ibdw_evowall_videoup' => 'Video',
'_ibdw_evowall_gruppoup' => 'Group',
'_ibdw_evowall_sondaggioup' => 'Poll',
'_ibdw_evowall_adsup' => 'Ads',
'_ibdw_evowall_sitoup' => 'Site',
'_ibdw_evowall_inseriscisito' => 'Link',
'_ibdw_evowall_inseriscisondaggio' => 'Enter Poll',
'_ibdw_evowall_inseriscifoto' => 'Insert photo',
'_ibdw_evowall_altrimetodi' => 'Other methods',
'_ibdw_evowall_soloio' => 'Only me',
'_ibdw_evowall_inseriscivideo' => 'Insert Video',
'_ibdw_evowall_altricommenti' => 'Show more',
'_ibdw_evowall_member_news' => 'News Feed',
'_ibdw_evowall_profile_news' => 'News Feed',
'_ibdw_evowall_second' => 'Please Wait',
'_ibdw_evowall_send' => 'Share',
'_ibdw_evowall_delete' => 'Delete',
'_ibdw_evowall_messstyle1' => '<div id="mstyle">',
'_ibdw_evowall_messstyle2' => '</div>',
'_ibdw_evowall_bx_ads_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared an ad <a href="{ads_url}">{ads_caption}</a></span>',
'_ibdw_evowall_bx_blogs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_bx_sounds_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a music <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_bx_video_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a video <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_bx_gruppo_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a group <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_photo_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a photo <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_bx_poll_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a poll <a href="{poll_url}">{poll_caption}</a></span>',
'_ibdw_evowall_bx_site_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a site <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_bx_event_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared an event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_ue30_event_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared an event <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_modzzz_property_share' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">shared the property <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_ue30_locations_add_condivisione' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">shared the location <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_messaggio' => 'posted a personal message',  
'_ibdw_evowall_videoalbum' => 'Wall-Video', 
'_ibdw_evowall_fotoalbum' => 'Wall-Photo',
'_ibdw_evowall_bx_share_title' => 'You shared content',
'_ibdw_evowall_bx_share_message' => 'Content has been shared successfully.',
'_ibdw_evowall_bx_access_denied' => 'Private: you dont have the right to access this content!',
'_ibdw_evowall_bx_video_under' => 'added a new video:',
'_ibdw_evowall_bx_video_undernotify' => '(this video will be available when approved)',
'_ibdw_evowall_bx_alert_notify' => 'You dont have permission to post this message',
'_ibdw_evowall_elementlike1' => 'people',
'_ibdw_evowall_elementlike2' => 'like this',
'_ibdw_evowall_friendlike' => 'Add to your Friends',
'_ibdw_evowall_friendlike2' => 'Request sent',
'_ibdw_evowall_ilikeit' => 'You like this',
'_ibdw_evowall_thiselementlike' => 'Like:',
'_ibdw_evowall_likeand' => 'and',
'_ibdw_evowall_likeyou' => 'You',
'_ibdw_evowall_likethis' => 'Like!',
'_ibdw_evowall_sender' => 'Share',
'_ibdw_evowall_unlikethis' => 'Unlike!',
'_ibdw_evowall_mutualfriend' => 'mutual friends',
'_ibdw_evowall_mutualfriendonlyone' => 'mutual friend',
'_ibdw_evowall_msgformhome' => 'What are you thinking or doing?',
'_ibdw_evowall_sicurity' => '<div style="padding:20px;color:red;">The EVO Wall (NEWS FEED) is not active, you must insert a valid activation code.<br>Visit the module configurator to get and insert the activation code.<br><br>This message is visible only to the administrator</div>',
'_ibdw_evowall_updater' => 'Update completed successfully',
'_ibdw_evowall_unsure' => 'NOT (Back)',
'_ibdw_evowall_activaintro' => 'EVO Wall activation\'s procedure',    
'_ibdw_evowall_spycodereq' => 'activation\'s code request',
'_ibdw_evowall_yosattiva' => 'Attention, your copy of EVO Wall is already active!',
'_ibdw_evowall_introattivazione' => 'TO ACTIVATE EVO WALL YOU NEED INSERT THE SAME EMAIL ADRESS (PAYPAL/ECHECK) USED FOR MODULE\'S PURCHASING AND THEN CLICK \'\'SEND REQUEST\'\'. YOU WILL RECEIVE AN EMAIL AT THE SAME ADDRESS CONTAINING THE ACTIVATION\'S CODE. THEN INSERT THIS CODE AND CLICK THE BUTTON \'ACTIVATE\'',
'_ibdw_evowall_uploadfrompc' => 'Upload from your Computer',
'_ibdw_evowall_useflash' => 'Use flash',
'_ibdw_evowall_iveright' => 'I have the right to distribute these photos',
'_ibdw_evowall_continue' => 'Continue',
'_ibdw_evowall_example' => 'Example',
'_ibdw_evowall_exlinkyb' => 'http://www.youtube.com/watch?v=_AANZvYn5uk',
'_ibdw_evowall_infocoferma1' => 'Is this (',
'_ibdw_evowall_infocoferma2' => ') the same email you used to pay?',
'_ibdw_evowall_1step' => 'Step 1',
'_ibdw_evowall_2step' => 'Step 2',
'_ibdw_evowall_eml_t_add' => 'Insert your email address (Paypal/Echeck)',
'_ibdw_evowall_send_rqs' => 'Send Request',
'_ibdw_evowall_conf_email_pay' => 'YES',
'_ibdw_evowall_bott_elimina_1' => 'Delete Post',
'_ibdw_evowall_bott_elimina_2' => 'Are you sure you want to delete this post?',
'_ibdw_evowall_bott_elimina_3' => 'Confirm',
'_ibdw_evowall_bott_elimina_4' => 'Cancel',
'_ibdw_evowall_bott_condividi_1' => 'Post to your Profile',
'_ibdw_evowall_bott_condividi_2' => 'Are you sure to share this post?',
'_ibdw_evowall_bott_condividi_3' => 'Share',
'_ibdw_evowall_bott_condividi_4' => 'Cancel',
'_ibdw_evowall_bott_notifica_1' => 'Information',
'_ibdw_evowall_bott_notifica_sharenotify' => 'This post has been shared into your profile\'s wall',
'_ibdw_evowall_bott_notifica_2' => 'Ok',
'_ibdw_evowall_notifica_condivisioneok' => 'The content has been shared',
'_ibdw_evowall_mywall' => 'My Wall',
'_ibdw_evowall_wallof' => '',
'_ibdw_evowall_wallprofile' => '\'s Wall',
'_ibdw_evowall_notificaupdate' => 'Updating...',
'_ibdw_evowall_notificalikefriend' => 'Your request has been sent. Wait the confirmation',
'_ibdw_evowall_selectfiles' => 'Select File',
'_ibdw_evowall_cancellupload' => 'Cancel Upload',
'_ibdw_evowall_dateprev' => '',
'_ibdw_evowall_share_album' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared the album <a href="{album_url}">{album_caption}</a></span>',
'_ibdw_evowall_comment_album' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the album <a href="{album_url}">{album_caption}</a></span>',
'_ibdw_evowall_linktoyoutube' => 'Link to embeded video',
'_ibdw_evowall_uploadfromyoutube' => 'Upload from YouTube',
'_ibdw_evowall_bx_evowall_message' => '<a href="{sender_p_link}">{sender_p_nick}</a> has sent a message to <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_bx_evowall_messageseitu' => '<a href="{sender_p_link}">{sender_p_nick}</a> has sent a message',
'_ibdw_evowall_urlspecial' => 'Insert URL:',
'_ibdw_evowall_url' => 'Url',
'_ibdw_evowall_selezionapreview' => 'Select preview:',
'_ibdw_evowall_totpreview1' => 'There are ',
'_ibdw_evowall_totpreview2' => ' images',
'_ibdw_evowall_totpreview1s' => 'There is ',
'_ibdw_evowall_totpreview2s' => ' image',
'_ibdw_evowall_totpreviewno' => 'No image available for this site',
'_ibdw_evowall_erroreurl' => 'Error: this URL seems to be not valid or the site is offline.<br/><a href="javascript:url();">Click here to try again</a>',
'_ibdw_evowall_nopreview' => 'No preview',
'_ibdw_evowall_bx_url_add' => '<a href="{sender_p_link}">{sender_p_nick}</a> added the site: <a href="{indirizzo}" target="_blank">{indirizzo}</a>',
'_ibdw_evowall_bx_url_share' => '<a href="{sender_p_link}">{sender_p_nick}</a> shared the site: <a href="{indirizzo}" target="_blank">{indirizzo}</a>',
'_ibdw_evowall_introcontent' => 'Share',
'_ibdw_evowall_notify_comment_photo' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">photo</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_video' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">video</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_poll' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">poll</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_groups' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">group</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_events' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented an <a href="{url}">event</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_sites' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">site</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_ads' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented an <a href="{url}">ad</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a post of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_blogs' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">blog</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_sounds' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">sound</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_ue30location' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">location</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_modzzz_property' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">property</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_url' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">url</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_photo' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">photo</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_video' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">video</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_poll' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">poll</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_groups' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">group</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_events' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes an <a href="{url}">event</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_sites' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">site</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_ads' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes an <a href="{url}">ad</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a post of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_blogs' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">blog</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_sounds' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">sound</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_ue30location' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">location</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_modzzz_property' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">property</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_url' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">url</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_photo_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{album_url}">photo</a>',
'_ibdw_evowall_notify_comment_video_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">video</a>',
'_ibdw_evowall_notify_comment_poll_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">poll</a>',
'_ibdw_evowall_notify_comment_groups_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">group</a>',
'_ibdw_evowall_notify_comment_events_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented an <a href="{url}">event</a></a>',
'_ibdw_evowall_notify_comment_sites_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">site</a>',
'_ibdw_evowall_notify_comment_ads_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented an <a href="{url}">ad</a>',
'_ibdw_evowall_notify_comment_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a your own post',
'_ibdw_evowall_notify_like_photo_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">photo</a>',
'_ibdw_evowall_notify_like_video_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">video</a>',
'_ibdw_evowall_notify_like_poll_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">poll</a>',
'_ibdw_evowall_notify_like_groups_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">group</a>',
'_ibdw_evowall_notify_like_events_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes an <a href="{url}">event</a>',
'_ibdw_evowall_notify_like_sites_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a <a href="{url}">site</a>',
'_ibdw_evowall_notify_like_ads_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes an <a href="{url}">ad</a>',
'_ibdw_evowall_notify_like_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> likes a your own post',
'_ibdw_evowall_welcome_title' => 'Welcome!! ',
'_ibdw_evowall_welcome_message' => 'Now you are part of this social network. You can edit your profile, add photos and videos, make new friendship and partecipate to the events of this community. Insert the details of your profile, this will help you to know the profiles similar to you.',
'_ibdw_evowall_welcome_hidemessage' => 'Hide this message',
'_ibdw_evowall_Privacy_Comment' => 'Allow comments to',
'_ibdw_evowall_Privacy_Like' => 'Allow like to',
'_ibdw_evowall_Privacy_ContentBox' => 'Allow dashboard to',
'_ibdw_evowall_Privacy_View' => 'Allow viewing to',
'_ibdw_evowall_Allow_share' => 'Allow share to',
'_ibdw_evowall_facebook_share_p' => 'Allow Facebook share to',
'_ibdw_evowall_twitter_share_p' => 'Allow Twitter share to',
'_ibdw_evowall_google_share_p' => 'Allow Google+ share to',
'_ibdw_evowall_linkedin_share_p' => 'Allow LinkedIn share to',
'_ibdw_evowall_pinterest_share_p' => 'Allow Pinterest share to',
'_ibdw_evowall_baidu_share_p' => 'Allow Baidu share to',
'_ibdw_evowall_weibo_share_p' => 'Allow Weibo share to',
'_ibdw_evowall_qzone_share_p' => 'Allow Qzone share to',
'_ibdw_evowall_facebook_share' => 'Facebook share',
'_ibdw_evowall_linkedin_share' => 'LinkedIn share',
'_ibdw_evowall_twitter_share' => 'Twitter share',
'_ibdw_evowall_google_share' => 'Google+ share',
'_ibdw_evowall_pinterest_share' => 'Pinterest share',
'_ibdw_evowall_baidu_share' => 'Baidu share',
'_ibdw_evowall_weibo_share' => 'Weibo share',
'_ibdw_evowall_qzone_share' => 'Qzone share',
'_ibdw_evowall_urlmess' => ' added the link: ',
'_ibdw_evowall_surlmess' => ' shared the link: ',
'_ibdw_evowall_closelink' => 'Cancel',
'_ibdw_evowall_justmessage' => 'Message only',
'_ibdw_evowall_messageandpreview' => 'Share all',
'_ibdw_evowall_maximize' => 'Click here to enlarge this photo',
'_ibdw_evowall_minimize' => 'Click on the picture to minimize the image',
'_ibdw_evowall_allcomm' => 'Show all ',
'_ibdw_evowall_allcomm2' => ' comments',
'_ibdw_evowall_parent_photo' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added {number} new photos',
'_ibdw_evowall_event_start' => 'Event start: ',
'_ibdw_evowall_event_end' => 'Event end: ',
'_ibdw_evowall_similarevonews_photo' => 'See other {number} similar posts in details',
'_ibdw_evowall_similarevonews' => 'See another similar post',
'_ibdw_evowall_mostpopular' => 'Most Popular',
'_ibdw_evowall_mostrecent' => 'News',
'_ibdw_evowall_newsupdate' => 'Update',
'_ibdw_evowall_currency_price' => '$ ',
'_ibdw_evowall_alertprivacyprofileview' => 'This wall is private',
'_ibdw_evowall_wait_button' => 'Wait',
'_ibdw_evowall_alertprivacyprofileviewexplain' => '{ProfileName} allows the view own wall just to certain members of this site',
'_ibdw_evowall_comment_nphoto_multi' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented the photos</span>',
'_ibdw_evowall_rate_photo_multi' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the photos</span>',
'_ibdw_evowall_clubs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">created the club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_clubs_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_clubs_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined the club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_clubs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the club <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_clubs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_clubs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_clubs' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">club</a>',
'_ibdw_evowall_notify_like_modzzz_clubs' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">club</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_petitions_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">created the petition <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_petitions_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the petition <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_petitions_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined the petition <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_petitions_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the petition <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_petitions_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the petition <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_petitions_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a petition <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_petitions' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">petition</a>',
'_ibdw_evowall_notify_like_modzzz_petitions' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">petition</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_pets_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added the pet <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_pets_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the pet <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_pets_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the pet <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_pets_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the pet <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_pets_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a pet <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_pets' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">pet</a>',
'_ibdw_evowall_notify_like_modzzz_pets' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">pet</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_bands_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added the band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bands_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bands_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined the band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bands_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the band <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_bands_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_bands_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_bands' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">band</a>',
'_ibdw_evowall_notify_like_modzzz_bands' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">band</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_schools_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added the school <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_schools_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the school <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_schools_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined the school <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_schools_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the school <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_schools_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the school <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_schools_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a school <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_schools' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">school</a>',
'_ibdw_evowall_notify_like_modzzz_schools' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">school</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notices_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added the notice <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notices_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the notice <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notices_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the notice <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_notices_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the notice <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_notices_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a notice <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_notices' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">notice</a>',
'_ibdw_evowall_notify_like_modzzz_notices' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">notice</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_classified_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added the classified <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_classified_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the classified <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_classified_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the classified <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_classified_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the classified <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_classified_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a classified <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_classified' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">classified</a>',
'_ibdw_evowall_notify_like_modzzz_classified' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">classified</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_news_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added the news <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_news_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed the news <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_news_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated the news <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_news_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented on the news <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_news_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared a news <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_news' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">news</a>',
'_ibdw_evowall_notify_like_modzzz_news' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">news</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_jobs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added new job <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_jobs_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed job <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_jobs_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined job <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_jobs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated job <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_jobs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented job <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_jobs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared job <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_jobs' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented <a href="{url}">job</a>',
'_ibdw_evowall_notify_like_modzzz_jobs' => '<a href="{sender_p_link}">{sender_p_nick}</a> like <a href="{url}">job</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_listing_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">added new business listing <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_listing_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">changed business listing <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_listing_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">joined listing <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_listing_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">rated business listing <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_listing_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">commented business listing <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_listing_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">shared business listing <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_listing' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented <a href="{url}">business listing</a>',
'_ibdw_evowall_notify_like_modzzz_listing' => '<a href="{sender_p_link}">{sender_p_nick}</a> like <a href="{url}">business listing</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_like_yown' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> like the photo <a href="{album_url}"><b>{album_caption}</b></a>',
'_ibdw_evowall_not_allowed' => 'This module is not allowed, please confirm your registrantion',
'_mma_EVO_WALL_-_Ads' => 'EVO WALL - Ads',
'_mma_EVO_WALL_-_Blogs' => 'EVO WALL - Blogs',
'_mma_EVO_WALL_-_Comments_add' => 'EVO WALL - Comments add',
'_mma_EVO_WALL_-_Comments_view' => 'EVO WALL - Comments view',
'_mma_EVO_WALL_-_Content_Box' => 'EVO WALL - Content Box',
'_mma_EVO_WALL_-_Events' => 'EVO WALL - Events',
'_mma_EVO_WALL_-_Groups' => 'EVO WALL - Groups',
'_mma_EVO_WALL_-_Like_add' => 'EVO WALL - Like add',
'_mma_EVO_WALL_-_Like_view' => 'EVO WALL - Like view',
'_mma_EVO_WALL_-_Personal_messages' => 'EVO WALL - Personal messages',
'_mma_EVO_WALL_-_Photos' => 'EVO WALL - Photos',
'_mma_EVO_WALL_-_Polls' => 'EVO WALL - Polls',
'_mma_EVO_WALL_-_Post_sharing' => 'EVO WALL - Post sharing',
'_mma_EVO_WALL_-_Sites' => 'EVO WALL - Sites',
'_mma_EVO_WALL_-_Sounds' => 'EVO WALL - Sounds',
'_mma_EVO_WALL_-_Videos' => 'EVO WALL - Videos',
);