<?
/**********************************************************************************
*                            IBDW EvoWall for Dolphin Smart Community Builder
*                              -------------------
*     begin                : July 23 2012
*     copyright            : (C) 2012 IlBelloDelWEB.it di Ferraro Raffaele Pietro
*     website              : http://www.ilbellodelweb.it
* This file was created but is NOT part of Dolphin Smart Community Builder 7
*
* IBDW EvoWall is not free and you cannot redistribute and/or modify it.
* 
* IBDW EvoWall is protected by a commercial software license.
* The license allows you to obtain updates and bug fixes for free.
* Any requests for customization or advanced versions can be requested 
* at the email info@ilbellodelweb.it. You can modify freely only your language file
* 
* For more details see license.txt file; if not, write to info@ilbellodelweb.it
**********************************************************************************/
$sLangCategory = 'evowall';
$aLangContent = array(
'_sys_module_evowall' => 'Notizie',
'_ibdw_evowall_informations'  => 'IBDW EvoWall informazioni',
'_ibdw_evowall_information_block' => 'Per ottenere la tua "License Key" (Activation Code), clicca il <a target="_blank" href="ibdw/evowall/activation.php">QUI</a><br /><br />Ricorda di inserire <b>lo stesso indirizzo email utilizzato per pagare questo modulo</b>.<br /><br />Dopo aver completato questi passaggi controlla la tua email e copia il codice nel primo campo del seguente form:',
'_ibdw_evowall_comment_add' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">ha aggiunto un commento a <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_member_subscribed' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">si è  iscritto</span>',
'_ibdw_evowall_spyprofile' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">ha visto il profilo di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_profile_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha cambiato il proprio profilo</span>',
'_ibdw_evowall_profile_rate' => '<a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> <span class="actionx">ha votato il profilo <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_isfriend' => '<a class="usernamestyle" href="{recipient_p_link}">{recipient_p_nick}</a> <span class="actionx">ha stretto amicizia con <a href="{sender_p_link}">{sender_p_nick}</a></span>',
'_ibdw_evowall_site_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato il sito <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_site_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato il sito <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_site_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato il sito <a href="{site_url}">{site_caption}</a></span>',	
'_ibdw_evowall_comment_nphoto' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato la <a href="{entry_url}">foto</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_comment_name' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato il <a href="{entry_url}">video</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_rated_videos' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato il <a href="{entry_url}">video</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_reply_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha risposto al <a href="{entry_url}">sondaggio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_rated_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato il <a href="{entry_url}">sondaggio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_comment_polls' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato il <a href="{entry_url}">sondaggio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_rate_photo' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la <a href="{entry_url}">foto</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_ads_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato l\'annuncio <a href="{ads_url}">{ads_caption}</a></span>',
'_ibdw_evowall_ads_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto un nuovo annuncio <a href="{ads_url}">{ads_caption}</a></span>',
'_ibdw_evowall_blogs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato il blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_blogs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto il blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_blogs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato il blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_sounds_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto una nuova musica <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_sounds_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato la <a href="{entry_url}">musica</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a></span>',
'_ibdw_evowall_sounds_rate'=> '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la musica <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_photo_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto una nuova foto <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_video_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto un nuovo video <a href="{video_url}">{entry_caption}</a></span>',
'_ibdw_evowall_site_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto un nuovo sito <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_group_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha creato il gruppo <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_group_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato il gruppo <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_group_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito al gruppo <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_group_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato il gruppo <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_group_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato il gruppo <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto un nuovo evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito all\'evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato l\'evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_event_edit' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato l\'evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_poll_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha creato il sondaggio <a href="{poll_url}">{poll_caption}</a></span>',
'_ibdw_evowall_original_size' => 'Guardala nel formato originale',
'_ibdw_evowall_event_name' => 'Eventi',
'_ibdw_evowall_group_forum' => 'Gruppo di discussione',
'_ibdw_evowall_oneminute' => 'circa un minuto fa',
'_ibdw_evowall_plusminutefirst' => 'circa ',
'_ibdw_evowall_plusminutesecond' => ' minuti fa',
'_ibdw_evowall_onehour' => 'circa un\'ora fa',
'_ibdw_evowall_plushourfirst' => 'circa ',
'_ibdw_evowall_plushoursecond' => ' ore fa',
'_ibdw_evowall_today' => 'oggi',
'_ibdw_evowall_yesterday' => 'ieri',
'_ibdw_evowall_otherday' => 'il ',
'_ibdw_evowall_now' => 'adesso',
'_ibdw_evowall_comment_title_first' => 'Sii il primo',
'_ibdw_evowall_comment_title1' => 'C\'è  ',
'_ibdw_evowall_comment_title2' => 'Ci sono',
'_ibdw_evowall_comment_titlef1' => 'commento',
'_ibdw_evowall_comment_titlef2' => 'commenti',
'_ibdw_evowall_ins_comm' => 'Commento',
'_ibdw_evowall_condividi' => 'Condividi',
'_ibdw_evowall_altrenews' => 'Altre news',
'_ibdw_evowall_fotoup' => 'Foto',
'_ibdw_evowall_videoup' => 'Video',
'_ibdw_evowall_gruppoup' => 'Gruppi',
'_ibdw_evowall_sondaggioup' => 'Sondaggi',
'_ibdw_evowall_adsup' => 'Annunci',
'_ibdw_evowall_sitoup' => 'Siti',
'_ibdw_evowall_inseriscisito' => 'Link',
'_ibdw_evowall_inseriscisondaggio' => 'Inserisci sondaggio',
'_ibdw_evowall_inseriscifoto' => 'Inserisci foto',
'_ibdw_evowall_altrimetodi' => 'Altri metodi',
'_ibdw_evowall_soloio' => 'Solo io',
'_ibdw_evowall_inseriscivideo' => 'Inserisci video',
'_ibdw_evowall_altricommenti' => 'Mostra altro',
'_ibdw_evowall_member_news' => 'News Feed',
'_ibdw_evowall_profile_news' => 'News Feed',
'_ibdw_evowall_second' => 'Attendi',
'_ibdw_evowall_send' => 'Condividi',
'_ibdw_evowall_delete' => 'Cancella',
'_ibdw_evowall_messstyle1' => '<div id="mstyle">',
'_ibdw_evowall_messstyle2' => '</div>',
'_ibdw_evowall_bx_ads_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx"ha condiviso l\'annuncio <a href="{ads_url}">{ads_caption}</a></span>',
'_ibdw_evowall_bx_blogs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il blog <a href="{post_url}">{post_caption}</a></span>',
'_ibdw_evowall_bx_sounds_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la musica <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_bx_video_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il video <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_bx_gruppo_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il gruppo <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_photo_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la foto <a href="{entry_url}">{entry_caption}</a></span>',
'_ibdw_evowall_bx_poll_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il sondaggio <a href="{poll_url}">{poll_caption}</a></span>',
'_ibdw_evowall_bx_site_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il sito <a href="{site_url}">{site_caption}</a></span>',
'_ibdw_evowall_bx_event_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_ue30_event_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'evento <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_modzzz_property_share' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso un annuncio immobiliare <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_ue30_locations_add_condivisione' => '<a href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il luogo <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_messaggio' => 'ha inserito un messaggio personale',  
'_ibdw_evowall_videoalbum' => 'Wall-Video', 
'_ibdw_evowall_fotoalbum' => 'Wall-Photo',
'_ibdw_evowall_bx_share_title' => 'Hai condiviso il contenuto',
'_ibdw_evowall_bx_share_message' => 'Il contenuto è  stato condiviso con successo.',
'_ibdw_evowall_bx_access_denied' => 'Privato: non hai i permessi per accedere a questo contenuto!',
'_ibdw_evowall_bx_video_under' => 'ha aggiunto un nuovo video:',
'_ibdw_evowall_bx_video_undernotify' => '(questo video sarà disponibile dopo l\'approvazione dell\'amministratore)',
'_ibdw_evowall_bx_alert_notify' => 'Non hai il permesso di inviare questo messaggio',
'_ibdw_evowall_elementlike1' => 'persone',
'_ibdw_evowall_elementlike2' => 'a cui piace',
'_ibdw_evowall_friendlike' => 'Aggiungi ai tuoi amici',
'_ibdw_evowall_friendlike2' => 'Richiesta inviata',
'_ibdw_evowall_ilikeit' => 'Ti piace',
'_ibdw_evowall_thiselementlike' => 'Piace a:',
'_ibdw_evowall_likeand' => 'e',
'_ibdw_evowall_likeyou' => 'te',
'_ibdw_evowall_likethis' => 'Mi piace!',
'_ibdw_evowall_sender' => 'Condividi',
'_ibdw_evowall_unlikethis' => 'Non mi piace più !',
'_ibdw_evowall_mutualfriend' => 'amici in comune',
'_ibdw_evowall_mutualfriendonlyone' => 'amico in comune',
'_ibdw_evowall_msgformhome' => 'Cosa stai pensando o facendo?',
'_ibdw_evowall_sicurity' => '<div style="padding:20px;color:red;">EVO Wall (NEWS FEED) non è  attivo, devi inserire un codice di attivazione valido.<br>Visita la pagina di configurazione del modulo per ottenere ed inserire il codice.<br><br>Questo messaggio è  visibile solo all\'amministratore</div>',
'_ibdw_evowall_updater' => 'Aggiornamento completato con successo',
'_ibdw_evowall_unsure' => 'NO (Indietro)',
'_ibdw_evowall_activaintro' => 'EVO Wall procedura di attivazione',  
'_ibdw_evowall_spycodereq' => 'richiesta codice di attivazione',
'_ibdw_evowall_yosattiva' => 'Attenzione, la tua copia di EVO Wall è  già stata attivata!',
'_ibdw_evowall_introattivazione' => 'PER ATTIVARE EVO WALL E\' RICHIESTO DI INSERIRE L\'INDIRIZZO EMAIL PAYPAL/ECHECK USATO PER ACQUISTARE QUESTO MODULO E QUINDI CLICCARE SU \'\'SEND CODE REQUEST\'\'. RICEVERAI UNA EMAIL A QUESTO INDIRIZZO CON IL CODICE DI ATTIVAZIONE. QUINDI INSERISCI QUESTO CODICE E CLICCA SUL BOTTONE PER L\'ATTIVAZIONE',
'_ibdw_evowall_uploadfrompc' => 'Carica dal tuo computer',
'_ibdw_evowall_useflash' => 'Usa flash',
'_ibdw_evowall_iveright' => 'Ho i diritti di distribuire queste foto',
'_ibdw_evowall_continue' => 'Continua',
'_ibdw_evowall_example' => 'Esempio',
'_ibdw_evowall_exlinkyb' => 'http://www.youtube.com/watch?v=_AANZvYn5uk',
'_ibdw_evowall_infocoferma1' => 'Sicuri sia questo l\'indirizzo email',
'_ibdw_evowall_infocoferma2' => 'utilizzato per pagare?',
'_ibdw_evowall_1step' => 'Fase 1',
'_ibdw_evowall_eml_t_add' => 'Inserisci il tuo indirizzo email (Paypal/Echeck)',
'_ibdw_evowall_send_rqs' => 'Invia richiesta',
'_ibdw_evowall_conf_email_pay' => 'SI',
'_ibdw_evowall_bott_elimina_1' => 'Cancella Post',
'_ibdw_evowall_bott_elimina_2' => 'Sicuri di voler cancellare questo post?',
'_ibdw_evowall_bott_elimina_3' => 'Conferma',
'_ibdw_evowall_bott_elimina_4' => 'Annulla',
'_ibdw_evowall_bott_condividi_1' => 'Posta sul tuo Profilo',
'_ibdw_evowall_bott_condividi_2' => 'Sicuri di voler condividere questo post?',
'_ibdw_evowall_bott_condividi_3' => 'Condividi',
'_ibdw_evowall_bott_condividi_4' => 'Annulla',
'_ibdw_evowall_bott_notifica_1' => 'Informazione',
'_ibdw_evowall_bott_notifica_sharenotify' => 'Questo post è  stato condiviso sulla wall del tuo profilo',
'_ibdw_evowall_bott_notifica_2' => 'Ok',
'_ibdw_evowall_notifica_condivisioneok' => 'Contenuto condiviso con successo',
'_ibdw_evowall_mywall' => 'La mia wall',
'_ibdw_evowall_wallof' => 'La wall di ',
'_ibdw_evowall_wallprofile' => '',
'_ibdw_evowall_notificaupdate' => 'Aggiornamento...',
'_ibdw_evowall_notificalikefriend' => 'La tua richiesta è  stata inviata. Attendi la conferma',
'_ibdw_evowall_selectfiles' => 'Seleziona File',
'_ibdw_evowall_cancellupload' => 'Annulla Upload',
'_ibdw_evowall_dateprev' => '',
'_ibdw_evowall_share_album' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'album <a href="{album_url}">{album_caption}</a></span>',
'_ibdw_evowall_comment_album' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'album <a href="{album_url}">{album_caption}</a></span>',
'_ibdw_evowall_linktoyoutube' => 'Link al video',
'_ibdw_evowall_uploadfromyoutube' => 'Carica da YouTube',
'_ibdw_evowall_bx_evowall_message' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha inviato un messaggio a <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_bx_evowall_messageseitu' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha inviato un messaggio',
'_ibdw_evowall_urlspecial' => 'Inserisci URL:',
'_ibdw_evowall_url' => 'Url',
'_ibdw_evowall_selezionapreview' => 'Seleziona anteprima:',
'_ibdw_evowall_totpreview1' => 'Ci sono ',
'_ibdw_evowall_totpreview2' => ' immagini',
'_ibdw_evowall_totpreview1s' => 'C\'è  ',
'_ibdw_evowall_totpreview2s' => ' immagine',
'_ibdw_evowall_totpreviewno' => 'Nessuna immagine disponibile per questo sito',
'_ibdw_evowall_erroreurl' => 'Errore: questo URL sembra non essere valido o il sito è  offline.<br/><a href="javascript:url();">Clicca qui per riprovare</a>',
'_ibdw_evowall_nopreview' => 'Nessuna anteprima',
'_ibdw_evowall_bx_url_add' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha aggiunto il sito: <a href="{indirizzo}" target="_blank">{indirizzo}</a>',
'_ibdw_evowall_bx_url_share' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha condiviso il sito: <a href="{indirizzo}" target="_blank">{indirizzo}</a>',
'_ibdw_evowall_introcontent' => 'Condividi',
'_ibdw_evowall_notify_comment_photo' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">foto</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_video' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">video</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_poll' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">sondaggio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_groups' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">gruppo</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_events' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">evento</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_sites' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">sito</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_ads' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">annuncio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un post di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_blogs' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">blog</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_sounds' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">musica</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_ue30location' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">location</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_modzzz_property' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">proprietà</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_url' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">url</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_photo' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">foto</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_video' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">video</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_poll' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">sondaggio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_groups' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">gruppo</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_events' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">evento</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_sites' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">sito</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_ads' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">annuncio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un post di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_blogs' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">blog</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_sounds' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">musica</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_ue30location' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">location</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_modzzz_property' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">proprietà</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_like_url' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">url</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_photo_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{album_url}">foto</a>',
'_ibdw_evowall_notify_comment_video_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">video</a>',
'_ibdw_evowall_notify_comment_poll_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">sondaggio</a>',
'_ibdw_evowall_notify_comment_groups_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">gruppo</a>',
'_ibdw_evowall_notify_comment_events_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">evento</a></a>',
'_ibdw_evowall_notify_comment_sites_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">sito</a>',
'_ibdw_evowall_notify_comment_ads_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">annuncio</a>',
'_ibdw_evowall_notify_comment_yown' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un proprio post',
'_ibdw_evowall_notify_like_photo_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">foto</a>',
'_ibdw_evowall_notify_like_video_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">video</a>',
'_ibdw_evowall_notify_like_poll_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">sondaggio</a>',
'_ibdw_evowall_notify_like_groups_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">gruppo</a>',
'_ibdw_evowall_notify_like_events_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">evento</a>',
'_ibdw_evowall_notify_like_sites_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">sito</a>',
'_ibdw_evowall_notify_like_ads_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">annuncio</a>',
'_ibdw_evowall_notify_like_yown' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un proprio post',
'_ibdw_evowall_welcome_title' => 'Benvenuti!! ',
'_ibdw_evowall_welcome_message' => 'Adesso tu fai parte di questo social network. Puoi modificare il tuo profilo, aggiungere foto e video, fare nuove amicizie e partecipare agli eventi di questa community. Inserisci i dettagli del tuo profilo, questo ti aiuterà a conoscere profili simili a te.',
'_ibdw_evowall_welcome_hidemessage' => 'Nascondi questo messaggio',
'_ibdw_evowall_Privacy_Comment' => 'Consenti commenti a',
'_ibdw_evowall_Privacy_Like' => 'Consenti Mi piace a',
'_ibdw_evowall_Privacy_ContentBox' => 'Consenti di scrivere un messaggio a',
'_ibdw_evowall_Privacy_View' => 'Consenti di vedere i post a',
'_ibdw_evowall_Allow_share' => 'Consenti di condividere a',
'_ibdw_evowall_facebook_share' => 'Condividi su Facebook',
'_ibdw_evowall_linkedin_share' => 'Condividi su LinkedIn',
'_ibdw_evowall_twitter_share' => 'Condividi su Twitter',
'_ibdw_evowall_google_share' => 'Condividi su Google+',
'_ibdw_evowall_pinterest_share' => 'Condividi su Pinterest',
'_ibdw_evowall_baidu_share' => 'Condividi su Baidu',
'_ibdw_evowall_weibo_share' => 'Condividi su Weibo',
'_ibdw_evowall_qzone_share' => 'Condividi su Qzone',
'_ibdw_evowall_facebook_share_p' => 'Consenti di condividere su Facebook a',
'_ibdw_evowall_twitter_share_p' => 'Consenti di condividere su Twitter a',
'_ibdw_evowall_google_share_p' => 'Consenti di condividere su Google+ a',
'_ibdw_evowall_linkedin_share_p' => 'Consenti di condividere su LinkedIn a',
'_ibdw_evowall_pinterest_share_p' => 'Consenti di condividere su Pinterest a',
'_ibdw_evowall_baidu_share_p' => 'Consenti di condividere su Baidu a',
'_ibdw_evowall_weibo_share_p' => 'Consenti di condividere su Weibo a',
'_ibdw_evowall_qzone_share_p' => 'Consenti di condividere su Qzone a',
'_ibdw_evowall_urlmess' => ' ha aggiunto il link: ',
'_ibdw_evowall_surlmess' => ' ha condiviso il link: ',
'_ibdw_evowall_closelink' => 'Annulla',
'_ibdw_evowall_justmessage' => 'Solo messaggio',
'_ibdw_evowall_messageandpreview' => 'Condividi tutto',
'_ibdw_evowall_maximize' => 'Clicca qui per allargare la foto',
'_ibdw_evowall_minimize' => 'Clicca su questa immagine per rimpicciolire la foto',
'_ibdw_evowall_allcomm' => 'Mostra tutti i ',
'_ibdw_evowall_allcomm2' => ' commenti',
'_ibdw_evowall_parent_photo' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto {number} nuove foto',
'_ibdw_evowall_event_start' => 'Inizio evento: ',
'_ibdw_evowall_event_end' => 'Fine evento: ',
'_ibdw_evowall_similarevonews_photo' => 'Vedi gli altri {number} post simili in dettaglio',
'_ibdw_evowall_similarevonews' => 'Vedi un\'altro post simile',
'_ibdw_evowall_mostpopular' => 'Più  popolari',
'_ibdw_evowall_mostrecent' => 'Novità',
'_ibdw_evowall_newsupdate' => 'Aggiorna',
'_ibdw_evowall_currency_price' => '$ ',
'_ibdw_evowall_alertprivacyprofileview' => 'Questo wall è  privata',
'_ibdw_evowall_wait_button' => 'Attendi',
'_ibdw_evowall_alertprivacyprofileviewexplain' => '{ProfileName} consente di mostrare la propria wall solo a particolari membri di questo sito',
'_ibdw_evowall_comment_nphoto_multi' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato alcune foto</span>',
'_ibdw_evowall_rate_photo_multi' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato alcune foto</span>',
'_ibdw_evowall_clubs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha creato il club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_clubs_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato il club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_clubs_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito al club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_clubs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato club <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_clubs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato il club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_clubs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso il club <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_clubs' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">club</a>',
'_ibdw_evowall_notify_like_modzzz_clubs' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">club</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_petitions_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha inserito la petizione <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_petitions_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato la petizione <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_petitions_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito alla petizione <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_petitions_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la petizione <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_petitions_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato la petizione <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_petitions_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la petizione <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_petitions' => '<a href="{sender_p_link}">{sender_p_nick}</a> commented a <a href="{url}">petition</a>',
'_ibdw_evowall_notify_like_modzzz_petitions' => '<a href="{sender_p_link}">{sender_p_nick}</a> like a <a href="{url}">petition</a> of <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_pets_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto l\'animale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_pets_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato l\'animale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_pets_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato l\'animale <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_pets_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'animale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_pets_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'animale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_pets' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato <a href="{url}">un animale</a>',
'_ibdw_evowall_notify_like_modzzz_pets' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">animale</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_bands_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha inserito la band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bands_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato la band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bands_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito alla la band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bands_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la band <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_bands_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato la band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_bands_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la band <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_bands' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">petizione</a>',
'_ibdw_evowall_notify_like_modzzz_bands' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">petitzione</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_schools_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha inserito la scuola <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_schools_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato la scuola <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_schools_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito alla la scuola <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_schools_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la scuola <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_schools_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato la scuola <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_schools_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la scuola <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_schools' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">scuola</a>',
'_ibdw_evowall_notify_like_modzzz_schools' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">scuola</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notices_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha inserito la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notices_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notices_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito alla notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notices_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la notizia <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_notices_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_notices_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_notices' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">notizia</a>',
'_ibdw_evowall_notify_like_modzzz_notices' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">notizia</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_classified_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha inserito l\'annuncio <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_classified_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato l\'annuncio <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_classified_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito all\'annuncio <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_classified_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato l\'annuncio <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_classified_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'annuncio <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_classified_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'annuncio <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_classified' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato un <a href="{url}">annuncio</a>',
'_ibdw_evowall_notify_like_modzzz_classified' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace un <a href="{url}">annuncio</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_news_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha inserito la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_news_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_news_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aderito alla notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_news_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato la notizia <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_news_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'annuncio <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_news_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso la notizia <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_news' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato una <a href="{url}">notizia</a>',
'_ibdw_evowall_notify_like_modzzz_news' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace una <a href="{url}">notizia</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_jobs_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto una nuova offerta di lavoro <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_jobs_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha cambiato l\'offerta di lavoro <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_jobs_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">&egrave; fan dell\'offerta di lavoro <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_jobs_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato l\'offerta di lavoro <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_jobs_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'offerta di lavoro <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_jobs_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'offerta di lavoro <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_jobs' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato l\'<a href="{url}">offerta di lavoro</a>',
'_ibdw_evowall_notify_like_modzzz_jobs' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace l\'<a href="{url}">offerta di lavoro</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_listing_add' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha aggiunto la nuova attivit&agrave; commerciale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_listing_editaw' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha modificato l\'attivit&agrave; commerciale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_listing_join' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">&egrave; fan dell\'attivit&agrave; commerciale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_listing_rate' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha votato l\'attivit&agrave; commerciale <a href="{entry_url}">{entry_title}</a></span>', 
'_ibdw_evowall_listing_comment' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha commentato l\'attivit&agrave; commerciale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_bx_listing_add_condivisione' => '<a class="usernamestyle" href="{profile_link}">{profile_nick}</a> <span class="actionx">ha condiviso l\'attivit&agrave; commerciale <a href="{entry_url}">{entry_title}</a></span>',
'_ibdw_evowall_notify_comment_modzzz_listing' => '<a href="{sender_p_link}">{sender_p_nick}</a> ha commentato l\'<a href="{url}">attivit&agrave; commerciale</a>',
'_ibdw_evowall_notify_like_modzzz_listing' => 'A <a href="{sender_p_link}">{sender_p_nick}</a> piace l\'<a href="{url}">attivit&agrave; commerciale</a> di <a href="{recipient_p_link}">{recipient_p_nick}</a>',
'_ibdw_evowall_notify_comment_like_yown' => 'A <a class="usernamestyle" href="{sender_p_link}">{sender_p_nick}</a> piace la foto <a href="{album_url}"><b>{album_caption}</b></a>',
'_ibdw_evowall_not_allowed' => 'Accesso al modulo non consentito, per cortesia conferma la tua registrazione',
'_mma_EVO_WALL_-_Ads' => 'EVO WALL - Annunci',
'_mma_EVO_WALL_-_Blogs' => 'EVO WALL - Blog',
'_mma_EVO_WALL_-_Comments_add' => 'EVO WALL - Aggiunta commenti',
'_mma_EVO_WALL_-_Comments_view' => 'EVO WALL - Vista commenti',
'_mma_EVO_WALL_-_Content_Box' => 'EVO WALL - Box inserimento contenuti',
'_mma_EVO_WALL_-_Events' => 'EVO WALL - Eventi',
'_mma_EVO_WALL_-_Groups' => 'EVO WALL - Gruppi',
'_mma_EVO_WALL_-_Like_add' => 'EVO WALL - Consenti mi piace',
'_mma_EVO_WALL_-_Like_view' => 'EVO WALL - Vista mi piace',
'_mma_EVO_WALL_-_Personal_messages' => 'EVO WALL - Messaggi personali',
'_mma_EVO_WALL_-_Photos' => 'EVO WALL - Foto',
'_mma_EVO_WALL_-_Polls' => 'EVO WALL - Sondaggi',
'_mma_EVO_WALL_-_Post_sharing' => 'EVO WALL - Condivisione post',
'_mma_EVO_WALL_-_Sites' => 'EVO WALL - Siti',
'_mma_EVO_WALL_-_Sounds' => 'EVO WALL - Musiche',
'_mma_EVO_WALL_-_Videos' => 'EVO WALL - Video',
);